apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-app
  template:
    metadata:
      labels:
        app: springboot-app
    spec:
      containers:
        - name: springboot-app
          image: ahr06/hemanth-2001:FirstApi
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: DB_URL
              value: jdbc:mysql://mysql-service:3306/School
            - name: DB_USERNAME
              value: root
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD
---
apiVersion: v1                  # ← this was missing!
kind: Service
metadata:
  name: springboot-app
spec:
  type: NodePort
  selector:
    app: springboot-app
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30081